# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: ''  # Use the sha / tag you want to point at
  hooks:
  - id: eslint
    additional_dependencies:
    - eslint@7.16.0
    - eslint-plugin-import@2.22.1
    - eslint-plugin-node@11.1.0
    - eslint-plugin-promise@4.2.1
    - eslint-plugin-standard@5.0.0
    - eslint-plugin-svelte3@3.0.0
    files: \.(js|svelte)$
